global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'local-dev'

scrape_configs:
  - job_name: 'backend'
    honor_labels: false
    static_configs:
      - targets: ['backend:3000'] # container name + port from docker-compose

  - job_name: 'pushgateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - /etc/prometheus/rules/spin_alerts.yml
