# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - 'rules/*.yml'

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics'
    # service name inside docker-compose network
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'pushgateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']
