name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - main

env:
  NODE_VERSION: '18'

jobs:
  lint-and-test:
    name: lint • rng • tests • build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install
        run: npm ci

      - name: Run RNG property test
        run: npm run rng:test

      - name: Run unit tests (jest) (pass if no tests)
        run: npm test -- --passWithNoTests

      - name: Typecheck & build
        run: npm run build

      - name: Lint (allow temporary @typescript-eslint/no-explicit-any relax)
        run: npx eslint "src/**/*.ts" --rule '@typescript-eslint/no-explicit-any:0' --max-warnings=0

  idempotency:
    name: idempotency smoke test (optional)
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Ensure required secrets present (skip job if not)
        shell: bash
        run: |
          # secrets injected into environment below; if not provided, skip
          if [ -z "${{ secrets.DEV_BASE_URL }}" ] || [ -z "${{ secrets.DEV_API_TOKEN }}" ] || [ -z "${{ secrets.DEV_SESSION_ID }}" ]; then
            echo "One or more required secrets (DEV_BASE_URL, DEV_API_TOKEN, DEV_SESSION_ID) are not set. Skipping idempotency job."
            exit 0
          fi
          echo "Secrets present, continuing..."
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm ci
        run: npm ci

      - name: Run idempotency test script (against DEV)
        env:
          DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
          DEV_API_TOKEN: ${{ secrets.DEV_API_TOKEN }}
          DEV_SESSION_ID: ${{ secrets.DEV_SESSION_ID }}
        run: node ./scripts/idempotency_test.js

  k6-smoke:
    name: k6 smoke (optional, runs only when secrets provided)
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Ensure required secrets present (skip job if not)
        shell: bash
        run: |
          if [ -z "${{ secrets.DEV_BASE_URL }}" ] || [ -z "${{ secrets.DEV_API_TOKEN }}" ] || [ -z "${{ secrets.DEV_SESSION_ID }}" ]; then
            echo "One or more required secrets (DEV_BASE_URL, DEV_API_TOKEN, DEV_SESSION_ID) are not set. Skipping k6-smoke job."
            exit 0
          fi
          echo "Secrets present, continuing..."

      - name: Install k6 (docker)
        run: docker pull grafana/k6:latest

      - name: Run smoke with k6 (container)
        env:
          DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
          DEV_API_TOKEN: ${{ secrets.DEV_API_TOKEN }}
          DEV_SESSION_ID: ${{ secrets.DEV_SESSION_ID }}
          K6_VUS: '1'
          K6_DURATION: '10s'
          K6_DEV_BYPASS: 'true'
        run: |
          docker run --rm \
            -e DEV_BASE_URL="${DEV_BASE_URL}" \
            -e DEV_API_TOKEN="${DEV_API_TOKEN}" \
            -e DEV_SESSION_ID="${DEV_SESSION_ID}" \
            -e K6_VUS="${K6_VUS}" \
            -e K6_DURATION="${K6_DURATION}" \
            -v "${PWD}":/scripts \
            grafana/k6:latest run /scripts/k6/smoke.js --summary-export /scripts/smoke-summary.json

      - name: Upload k6 summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-summary
          path: smoke-summary.json
