name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build (TypeScript)
        run: npm run build

      - name: Run unit tests (jest)
        run: npm test -- --runInBand

      - name: RNG property test (small)
        run: npm run rng:property

  k6-smoke:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run k6 smoke via Docker
        env:
          DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
          DEV_API_TOKEN: ${{ secrets.DEV_API_TOKEN }}
          DEV_SESSION_ID: ${{ secrets.DEV_SESSION_ID }}
        run: |
          docker run --rm \
            -e DEV_BASE_URL="$DEV_BASE_URL" \
            -e DEV_API_TOKEN="$DEV_API_TOKEN" \
            -e DEV_SESSION_ID="$DEV_SESSION_ID" \
            -v "${{ github.workspace }}:/test" \
            -w /test \
            grafana/k6:latest run ./k6/smoke.js
